#!/usr/bin/env node
var sys = require('sys')
var spawn = require('child_process').spawn;

//Commands
var PATH  = __dirname + "/node_modules/.bin"
var COMMANDS  = {  "start" : PATH + "/grunt", "create" : PATH + "/yo cean", "add" : PATH + "/yo cean",  "install" : "npm install" };

/**
 * Usage details
 */
function usage() {

	console.log("Use: cean-cli {install|run|create|add} {args}");
}

/**
 * Entry point of the CLI
 */
function main() {

   //console.log("Execution envirnment is " + PATH + " .");
   var args = process.argv;
   //console.log( "Args are: " + args);

   if (args.length >= 3) {

	cmd = args[2];

	if ( cmd !== "--help" ) {

		mcmd = COMMANDS[cmd];
		
		if (typeof mcmd !== "undefined")
		{
	
			cargs = args.slice(3).join(' ');

			//console.log("args = " + cargs); 			

			strcmd = mcmd;

			//Pass the arguments and construct the execution command
			if ( cargs !== "" ) { 

				//Default argument delimitter
				delim = " ";

				//For sub generators use ':' as delim
				if (cmd == "add") {
					
					delim = ":";
				}
				
				strcmd = strcmd + delim + cargs;
				
				//For create append the bower init command
				if ( cmd == "create") {
				
					strcmd = strcmd + ";" + PATH + "/bower install";
				}
			}
		
			console.log("cean-cli - Executing: " + strcmd);			

			spawn('sh', ['-c', strcmd], { stdio: 'inherit' });
		}
		else {
			console.error("This subcommand is not supported.");
			usage();
		}

	} else {

		usage();

	}
   } else {
   
      console.error("You have to pass a subcommand!");
      usage();
   }
}

main();
